### ISSUE TITLE
Getting error "AI provider openai not specified in configuration. Please run k8sgpt auth" while using k8sgpt cli with Azureopenai as backend

### ISSUE THREAD

**Issue by venkatest** [k8sgpt-ai/k8sgpt#1074]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.29

### Kubernetes Version

v1.29.1

### Host OS and its Version

Windows

### Steps to reproduce

![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/51379199/ddaa8df3-4922-4342-bbe8-381ecb77b4eb)

k8sgpt auth default -p azureopenai

k8sgpt auth add --backend azureopenai --baseurl https://xxxxxx.openai.azure.com --engine gpt3-5 --model gpt-35-turbo

![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/51379199/a1386e33-fbd5-44c8-ac55-030a2366ea1e)

![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/51379199/389050d0-ec4c-4cf4-96ff-49a057b902e9)

k8sgpt analyze --explain --filter=Pod

![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/51379199/1c98355a-7eba-48d5-bb2e-5d0f97b4196d)

### Expected behaviour

K8sgpt should give analyze results

### Actual behaviour

Error: AI provider openai not specified in configuration. Please run k8sgpt auth

### Additional Information

I checked this issue : https://github.com/k8sgpt-ai/k8sgpt-operator/issues/98 but didnt help

**Comment by strowi** [comment]
Having a similar issue with v0.3.40 + local ollama:

```bash
~> ollama serve &
~ » k8sgpt auth add --backend localai --model mistral --baseurl http://localhost:11434/v1
localai added to the AI backend provider list

~ » k8sgpt analyze --explain --filter=Service
Error: AI provider openai not specified in configuration. Please run k8sgpt auth
```

**Comment by raghu25** [comment]
try doing to switch to the desired backend

 k8sgpt auth default -p<backend ai>

**Comment by jlcrow** [comment]
I have this problem when running the Operator version 0.2.27 of the chart with v0.4.31 of K8sGPT using azureopenai backend, randomly my pod will start crashlooping with the "Error: AI provider openai not specified in configuration. Please run k8sgpt auth"  The issue only seems to happen with my set up in AKS

```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-dev-int-scan
  namespace: infra
spec:
  ai:
    enabled: true
    model: gpt-4o-mini
    engine: gpt-4o-mini
    backend: azureopenai
    baseUrl: https://<redacted>.cognitiveservices.azure.com
    anonymized: false
    secret:
      name: openai
      key: key
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.31
  analysis:
    interval: 6h
  extraOptions:
    backstage:
      enabled: true
  filters:
  - Job
  - StatefulSet
  - CronJob
  - Node
  - PodDisruptionBudget
  - Service
  - Pod
  - ConfigMap
  - PersistentVolumeClaim
  - Storage
  - ValidatingWebhookConfiguration
  - Deployment
  - ReplicaSet
  - MutatingWebhookConfiguration
  - HorizontalPodAutoscaler
  - Ingress
```
