### ISSUE TITLE
GitHub action for K8sgpt

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#137]

**Comment by AlexsJones** [comment]
Hi @shivamdurgbuns glad to hear. Let me fill some information

Scenario:
As an engineer
Given I use github actions to deploy a workload into a Kubernetes cluster
Then I should be able to use K8sGPT to scan for regressions

Example Action
```
  - uses: k8sgpt-ai/k8sgpt@v1
    with:
      auth: $OPENAI_KEY_SECRET
      kubernetes_config: $KUBECONFIG_SECRET
  - run: k8sgpt analyze
```

We could make it more elaborate and have `exit_on_failure` 
I don't mind making some code changes to help with this.

We already have an OCI ( docker image) for K8sGPT so getting started on this shouldn't be too hard.

@thschue did I miss anything?
