### ISSUE TITLE
[Question]: K8SGPT Cluster Operator

### ISSUE THREAD

**Issue by Ken501** [k8sgpt-ai/k8sgpt#1418]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [x] K8sGPT Operator

### Kubernetes Version

v1.30.10-eks-bc803b4

### Host OS and its Version

amazon-eks-node-1.30-v20250304

### Steps to reproduce

Introduce the following `k8sgpt` custom resource.

```yaml
---
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-bedrock
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    autoRemediation:
      enabled: true
      resources:
        - Pod
        - Deployment
        - Service
        - Ingress
      similarityRequirement: "90"
    # Removed to use IRSA instead of secret with AWS Access keys.
    # secret:
    #  name: bedrock-secret
    model: anthropic.claude-v2
    region: us-east-1
    backend: amazonbedrock
  noCache: true
  repository: xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.1
```

`values for k8sgpt-operator`

```yaml
## Optional enable distributed cache
interplex:
  enabled: false

serviceMonitor:
  enabled: false
  additionalLabels: {}
  # The namespace where Prometheus expects to find the serviceMonitor
  # namespace: ""
grafanaDashboard:
  enabled: false
  # The namespace where Grafana expects to find the dashboard
  # namespace: ""
  folder:
    annotation: grafana_folder
    name: ai
  label:
    key: grafana_dashboard
    value: "1"
  # create GrafanaDashboard custom resource referencing to the configMap.
  # according to https://grafana-operator.github.io/grafana-operator/docs/examples/dashboard_from_configmap/readme/
  grafanaOperator:
    enabled: false
    matchLabels:
      dashboards: "grafana"
controllerManager:
  kubeRbacProxy:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/quay.io/brancz/kube-rbac-proxy
      tag: v0.18.2
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    sinkWebhookTimeout: 30s
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/ghcr.io/k8sgpt-ai/k8sgpt-operator
      tag: v0.2.10  # x-release-please-version
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  ## Node labels for pod assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  #
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    # Set securityContext.runAsUser/runAsGroup if necessary. Values below were taken from https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/Dockerfile
    # runAsUser: 65532
    # runAsGroup: 65532
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP

```

`Installation command`:

```bash
helm upgrade --install k8sgpt-operator k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace --values k8sgpt-operator-values.yaml
```

### Expected behaviour

K8SGPT Operator continuously scans my EKS cluster and produces and updates `Results` Custom Resource based off cluster activity.

### Actual behaviour

Scans cluster for any issues and produces a single one time `Results` CR. This only shows issues present during time of deployment. If I introduce a new broken pod for example it does not continuously scan the cluster and/or produce a new or updated `Results` CR. If I also get rid of existing issues it is not reflected. 

### Additional Information

What is the point of the K8SGPT Operator as of today if it does not continously scan the cluster and update the Results CR? It's just better if I use the `K8SGPT` CLI but I want to find the potential for installing this. I like the idea of having an operator continuously scan my cluster but I can't find anywhere else on the documentation how the K8SGPT operator helps me vs just using its CLI. To trigger a new scan I effectively have to delete the `k8sgpt` Custom Resource I introduce and re-apply to trigger a new scan. I find this very counter productive unless I am misconfiguring it somehow?
