### ISSUE TITLE
[Bug]: pods terminated abnormally are not detected

### ISSUE THREAD

**Issue by gossion** [k8sgpt-ai/k8sgpt#1436]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [x] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.4.8

### Kubernetes Version

v1.30.10

### Host OS and its Version

Linux

### Steps to reproduce

I found that pods with Error state but Pod analyzer doesn't catch the problem

```
$ kubectl get po
NAME         READY   STATUS   RESTARTS   AGE
crash-test   0/1     Error    0          10s

$./k8sgpt analyze --filter=Pod
AI Provider: AI not used; --explain not set

No problems detected
```

It is easy to reproduce

1. create a crash-test pod (spec as below)
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: crash-test
spec:
  containers:
  - name: crash-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Crashing now...' && exit 1"]
    # Optional: prevent restarts for pure crash testing
  restartPolicy: Never
```
2. run k8sgpt analyzer
```
./k8sgpt analyze --filter=Pod -o json
```

### Expected behaviour

expect to catch the problem for that crash-test pod

### Actual behaviour

currently, No problems detected.
