### ISSUE TITLE
[Question]: Bedrock supported region list update

### ISSUE THREAD

**Issue by muralimeka** [k8sgpt-ai/k8sgpt#1463]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [x] K8sGPT (CLI)
- [x] K8sGPT Operator

### K8sGPT Version

v0.4.12

### Kubernetes Version

minikube version: v1.34.0

### Host OS and its Version

MacOS

### Steps to reproduce

I approached this test in two different approaches 1. Using K8sGPT cli 2. K8sGPT Operator and both of them gave me different errors but I am assuming the underlying reason might be unsupported region as I was trying to use us-gov-west-1 and this is not in BEDROCKER_SUPPORTED_REGION variable you use. 

1. Using K8sGPT cli on Mac
    a. Install K8sGPT CLI
        `brew tap k8sgpt-ai/k8sgpt`
        `brew install k8sgpt`
    b. Export AWS credentials including default region as us-gov-west-1
    c. Adding bedrock backend as auth
       ` k8sgpt auth add --backend amazonbedrock --model amazon.nova-lite-v1:0 --providerRegion us-gov-west-1`
    d. Install ([Minikube Install](https://minikube.sigs.k8s.io/docs/start/?arch=%2Fmacos%2Fx86-64%2Fstable%2Fbinary+download)) and Start a minikube cluster locally and run test workload with issues in deployment file
        `minikube start`
        `kubectl apply -f test-deployment.yaml`
    e. Analyze and explain using K8SGPT cli
        `k8sgpt analyze --explain --backend amazonbedrock`

I get an error "Error: failed while calling AI provider amazonbedrock: UnrecognizedClientException: The security token included in the request is invalid.  status code: 403, request id: xyz". Made sure my credentials had enough permission by performing 'aws bedrock-runtime invoke-model' and got a successful response.

2. K8sGPT Operator in minikube
    a. `minikube start`
    b. `helm install k8sgpt k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace`
    c. `kubectl create secret generic bedrock-sample-secret --from-literal=AWS_ACCESS_KEY_ID="$(echo $AWS_ACCESS_KEY_ID)" --from-literal=AWS_SECRET_ACCESS_KEY="$(echo $AWS_SECRET_ACCESS_KEY)" -n k8sgpt-operator-system`
    d. `kubectl apply -f k8sgpt/k8sgpt-bedrock.yaml`
      ```
      apiVersion: core.k8sgpt.ai/v1alpha1
      kind: K8sGPT
      metadata:
        name: k8sgpt-amazonbedrock
        namespace: k8sgpt-operator-system
      spec:
        extraOptions:
          backstage:
            enabled: true
        ai:
          enabled: true
          secret:
            name: bedrock-sample-secret
          model: amazon.nova-lite-v1:0
          region: us-gov-west-1
          backend: amazonbedrock
          anonymized: true
        noCache: true
        repository: ghcr.io/k8sgpt-ai/k8sgpt
        version: v0.4.1
        ```

When I check the logs for k8sgpt-amazonbedrock pod I see the below error 
server/log.go:50","msg":"request failed. model not found","duration_ms":6,"method":"/schema.v1.ServerAnalyzerService/Analyze","request":"backend:\"amazonbedrock\" explain:true anonymize:true nocache:true language:\"english\" max_concurrency:10 output:\"json\"","remote_addr":"1.2.3.4:1234","status_code":2}

### Expected behaviour

I expected to get results from analyze but in both the cases I never got any results and after certain debugging I think the issue is the supported regions for bedrock are not up to date.

### Actual behaviour

**Using CLI** 
I get an error "Error: failed while calling AI provider amazonbedrock: UnrecognizedClientException: The security token included in the request is invalid.  status code: 403, request id: xyz". Made sure my credentials had enough permission by performing 'aws bedrock-runtime invoke-model' and got a successful response.

**Using K8sgpt operator**
When I check the logs for k8sgpt-amazonbedrock pod I see the below error 
server/log.go:50","msg":"request failed. model not found","duration_ms":6,"method":"/schema.v1.ServerAnalyzerService/Analyze","request":"backend:\"amazonbedrock\" explain:true anonymize:true nocache:true language:\"english\" max_concurrency:10 output:\"json\"","remote_addr":"1.2.3.4:1234","status_code":2}

### Additional Information

Please update the list of supported bedrock regions with newly added support [Bedrock Feature Regions](https://docs.aws.amazon.com/bedrock/latest/userguide/features-regions.html)

Assuming the updated should happen here [BEDROCKER_SUPPORTED_REGION](https://github.com/k8sgpt-ai/k8sgpt/blob/main/pkg/ai/amazonbedrock.go#L47)

If you need anything else from my end please let me know. Thank you!
