### ISSUE TITLE
k8sgpt operator Failing to Detect New Failed Resources

### ISSUE THREAD

**Issue by kadhamecha-conga** [k8sgpt-ai/k8sgpt#1481]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [x] K8sGPT Operator

### Kubernetes Version

v1.30.9

### Host OS and its Version

eks

### Steps to reproduce

hi , 

* The controller does not appear to be continuously monitoring or scanning resources for state changes in near real-time.
* Specifically, newly provisioned Kubernetes resources that enter a failed state are not being detected by k8sgpt.
* Consequently, these undetected failed resources are not reflected in the k8sgpt overview dashboard.

backend local ai :

```
`apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-ollama
  namespace: test
spec:
  ai:
    enabled: true
    model: gemma3:12b
    backend: localai
    baseUrl: http://ollama:11434/v1 
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.13`
```

helm chart version :

```
releases:
  - name: k8sgpt
    namespace: test
    chart: k8sgpt/k8sgpt-operator
    version: 0.2.13
```

failed resource i'm trying : 
```

---
# failed-deployment-probe.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed-deployment-probe
  labels:
    app: bad-probe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-probe-app
  template:
    metadata:
      labels:
        app: bad-probe-app
    spec:
      containers:
      - name: main-container
        image: nginx:stable-alpine # A working image
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /this-path-does-not-exist # Readiness probe will fail
            port: 80
          initialDelaySeconds: 5 # Start checking after 5 seconds
          periodSeconds: 5     # Check every 5 seconds
          failureThreshold: 2  # Mark as NotReady after 2 failures
---
# failed-pod-crashloop.yaml
apiVersion: v1
kind: Pod
metadata:
  name: failed-pod-crashloop
  labels:
    app: crashy-app
spec:
  containers:
  - name: crashy-container
    image: busybox:latest # A small utility image
    command: ["/bin/sh", "-c", "echo 'About to crash...' && sleep 2 && exit 1"] # Command that fails
```

thanks.

### Expected behaviour

it should continuously scan for new resources and report it in k8sgpt overview dashboard if it fails.

### Actual behaviour

 scan for new resources is not happening, so new issue is not reporting in dashboard
