### ISSUE TITLE
[Bug] k8sgpt operator is not working with localai

### ISSUE THREAD

**Issue by vishalyadav6300** [k8sgpt-ai/k8sgpt#1524]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [x] K8sGPT Operator

### K8sGPT Version

v0.4.17

### Kubernetes Version

v1.27.1

### Steps to reproduce

1. Create a localai using ollama with model mistral 
     Running on  http://localhost:11434
2. Create a k8sgpt deployment
     
```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    backend: localai
    baseUrl: http://localhost:11434 
    model: mistral
    language: english
  noCache: false
  version: v0.3.41
```
3. Checking pod logs 
```
dev@datkube-devbox:~$ kubectl logs k8sgpt-local-c8976bc9b-jxjcb -n k8sgpt-operator-system -f
{"level":"info","ts":1749212850.491263,"caller":"server/server.go:146","msg":"binding metrics to 8081"}
{"level":"info","ts":1749212850.5029776,"caller":"server/server.go:105","msg":"binding api to 8080"}
{"level":"info","ts":1749212879.551298,"caller":"server/log.go:50","msg":"request failed. failed while calling AI provider localai: Post \"http://localhost:11434/chat/completions\": dial tcp [::1]:11434: connect: connection refused","duration_ms":9793,"method":"/schema.v1.ServerAnalyzerService/Analyze","request":"backend:\"localai\"  explain:true  anonymize:true  language:\"english\"  max_concurrency:10  output:\"json\"","remote_addr":"10.244.99.89:37258","status_code":2}
{"level":"info","ts":1749212888.98999,"caller":"server/log.go:50","msg":"request failed. failed while calling AI provider localai: Post \"http://localhost:11434/chat/completions\": dial tcp [::1]:11434: connect: connection refused","duration_ms":9416,"method":"/schema.v1.ServerAnalyzerService/Analyze","request":"backend:\"localai\"  explain:true  anonymize:true  language:\"english\"  max_concurrency:10  output:\"json\"","remote_addr":"10.244.99.89:53148","status_code":2}
```
It is saying, "request failed. failed while calling AI provider localai:"
4.  checking results, details attribute is empty
```
dev@datkube-devbox:~$ kubectl get results -o json -n k8sgpt-operator-system
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "core.k8sgpt.ai/v1alpha1",
            "kind": "Result",
            "metadata": {
                "creationTimestamp": "2025-06-06T09:16:11Z",
                "generation": 1,
                "labels": {
                    "k8sgpts.k8sgpt.ai/backend": "localai",
                    "k8sgpts.k8sgpt.ai/name": "k8sgpt-local",
                    "k8sgpts.k8sgpt.ai/namespace": "k8sgpt-operator-system"
                },
                "name": "defaultf5afm",
                "namespace": "k8sgpt-operator-system",
                "resourceVersion": "19920",
                "uid": "8cdebf60-00a7-45f9-b27f-3fed7a90b0c9"
            },
            "spec": {
                "backend": "localai",
                "details": "",
                "error": [
                    {
                        "sensitive": [
                            {
                                "masked": "O1Fz",
                                "unmasked": "app"
                            },
                            {
                                "masked": "M1FMKUEt",
                                "unmasked": "pod1"
                            }
                        ],
                        "text": "Service has no endpoints, expected label app=pod1"
                    }
                ],
                "kind": "Service",
                "name": "default/pod1",
                "parentObject": ""
            },
            "status": {
                "lifecycle": "historical"
            }
        },
```

### Expected behaviour

The details field should be filled by a local LLM.

**Comment by vishalyadav6300** [comment]
created ollama namespace
---------------------------
kubectl create ns ollama

Ollama deployment
-------------------
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama
        command: ["/bin/sh"]
        args:
          - -c
          - |
            ollama serve &
            sleep 5
            ollama pull mistral
            wait
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
```
-------

port-forward
-------------
```
kubectl port-forward -n ollama svc/ollama 11434:11434
```

deploy k8sgpt operator
------------------------
```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    backend: localai
    baseUrl: http://ollama.ollama.svc.cluster.local:11434 
    model: mistral
    language: english
  noCache: false
  version: v0.3.41
```

checking logs of k8sgpt pod
-----------------------------
```
dev@datkube-devbox:~$ kubectl logs k8sgpt-local-7c78ff498b-5rjjr -n k8sgpt-operator-system
{"level":"info","ts":1749447701.5431626,"caller":"server/server.go:146","msg":"binding metrics to 8081"}
{"level":"info","ts":1749447701.543406,"caller":"server/server.go:105","msg":"binding api to 8080"}
{"level":"info","ts":1749447713.3046184,"caller":"server/log.go:50","msg":"request failed. failed while calling AI provider localai: error, status code: 404, message: json: cannot unmarshal number into Go value of type openai.ErrorResponse","duration_ms":10029,"method":"/schema.v1.ServerAnalyzerService/Analyze","request":"backend:\"localai\"  explain:true  anonymize:true  language:\"english\"  max_concurrency:10  output:\"json\"","remote_addr":"10.244.99.89:40436","status_code":2}
{"level":"info","ts":1749447723.351876,"caller":"server/log.go:50","msg":"request failed. failed while calling AI provider localai: error, status code: 404, message: json: cannot unmarshal number into Go value of type openai.ErrorResponse","duration_ms":10022,"method":"/schema.v1.ServerAnalyzerService/Analyze","request":"backend:\"localai\"  explain:true  anonymize:true  language:\"english\"  max_concurrency:10  output:\"json\"","remote_addr":"10.244.99.89:49848","status_code":2}
```
checking result of pods
------------------------
```
dev@datkube-devbox:~$ kubectl get results -o json -n k8sgpt-operator-system
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": ""
    }
}
```
