### ISSUE TITLE
Break out the settings from the openAI client into config

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt#167]
We need to have at least the default model as a parameter that is in the config for long term support of models like davinci via openai
e.g.
```
ai:
 providers:
   - name: openai
      model: GPT3-turbo
```
