### ISSUE TITLE
Bug: k8sgpt generate in docker container fails to open browser except linux

### ISSUE THREAD

**Issue by VinayKadalagi** [k8sgpt-ai/k8sgpt#182]
Checklist:

* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've included steps to reproduce the bug.
* [x] I've included the version of Kubernetes and k8sgpt.

### Steps to reproduce

Command:
**docker run -v ~/.kube/config:/home/nonroot/.kube/config -v ~/.minikube:/Users/vinay/.minikube/ k8sgpt generate**                                        

Output:
```
Opening: https://beta.openai.com/account/api-keys to generate a key for openai
Please copy the generated key and run `k8sgpt auth` to add it to your config file

exec: "xdg-open": executable file not found in $PATH
```
### Your environment

Darwin / MacOS

* Version of Kubernetes
```
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

* Host OS and its version / If windows, is it WSL?
```
MacOS Ventura Version 13.2.1
```
* Version of k8sgpt
`k8sgpt version dev`

### Expected behaviour
Default browser should open the given URL.

### Actual behaviour

Errors out: `xdg-open command not found` since `runtime.GOOS` is always `linux` as it is running inside container.

**Comment by AlexsJones** [comment]
Typically, I'd anticipate you mount the secret into the docker container rather than trying to generate it inside e.g.
 ```
version: '2'
services:
  k8sgpt:
    image: ghcr.io/k8sgpt-ai/k8sgpt:dev-202304011623
    volumes:
      -  /home/$(whoami)/.k8sgpt.yaml:/home/root/.k8sgpt.yaml
```

However you are right it's a bug, but perhaps we just hide the error message if `xdg-open` has not been found?
