### ISSUE TITLE
[Bug]: k8sgpt fails to start with "mkdir /.config: permission denied"

### ISSUE THREAD

**Issue by jkleinlercher** [k8sgpt-ai/k8sgpt#440]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] #470

### K8sGPT Version

v0.3.0

### Kubernetes Version

v1.24.0

### Steps to reproduce

Environment: OpenShift 4.11 with SCC enabled

Steps to reproduce:

1. install k8sgpt on K8s cluster with operator like described in https://github.com/k8sgpt-ai/k8sgpt-operator
2. provide secret and K8sGPT CR described in https://github.com/k8sgpt-ai/k8sgpt-operator#run-the-example
3. k8sgpt fails to start. Logs show as follows
```
kubectl logs k8sgpt-deployment-877c6ddd9-2cx5z
Error: mkdir /.config: permission denied
```

The pod runs by default with "restricted-v2" SCC (https://docs.openshift.com/container-platform/4.11/authentication/managing-security-context-constraints.html). I guess this could be the reason.

securityContext of k8sgpt pod:

```
  securityContext:
    fsGroup: 1000980000
    seLinuxOptions:
      level: s0:c31,c25
    seccompProfile:
      type: RuntimeDefault
```

and securityContext of the container:

```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000980000
```

### Expected behaviour

K8sGPT should run also on OpenShift with SCC enabled.

### Actual behaviour

K8sGPT fails to start on OpenShift 4.11 with SCC enabled.
