### ISSUE TITLE
Error: exhausted API quota for AI provider openai: error, status code: 429, message: Rate limit reached for default-gpt-3.5-turbo[Question]: <Question Title>

### ISSUE THREAD

**Issue by rohanmathias** [k8sgpt-ai/k8sgpt#543]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

0.3.9

### Host OS and its Version

windows 10

### Steps to reproduce

1. k8sgpt auth add --backend openai -m gpt-3.5-turbo
2. k8sgpt analyse (works as expected)
3. k8sgpt analyse --explain **(Issue)**

### Expected behaviour

K8sgpt analyze explain command should be able to provide details on failures or suggestion

### Actual behaviour

k8sgpt analyse --explain
  21% |███████████████████████                                                                                          | (4/19, 7 it/min) [34s:2m3s]
Error: exhausted API quota for AI provider openai: error, status code: 429, message: Rate limit reached for default-gpt-3.5-turbo in organization org-mvY8Tb93IM7oATqDyd9m347q on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

**Comment by nitishfy** [comment]
This has been answered over slack.

**Comment by mitchross** [comment]
> This has been answered over slack.

What was the solution?

**Comment by danil2308** [comment]
https://platform.openai.com/docs/guides/error-codes/api-errors

**Comment by RaceFPV** [comment]
For anyone else running into this issue, since this is the first search result... you need to update the k8sgpt openai auth, not just try to set the config.

`k8sgpt auth update openai -m gpt-3.5-turbo -p <yourapikey>`

api keys can be found/generated from here: https://platform.openai.com/api-keys

**Comment by DevOpsPop** [comment]
still have the same error 
```
k8sgpt: 0.4.17 (306b3c9)
ai:
    providers:
        - name: openai
          model: gpt-3.5-turbo
          password: <blank>
          temperature: 0.7
          topp: 0.5
          topk: 50
          maxtokens: 2048
          customheaders: []
    defaultprovider: "openai"
```
