### ISSUE TITLE
[Feature]: add trivy configauditreport analyzes

### ISSUE THREAD

**Issue by jkleinlercher** [k8sgpt-ai/k8sgpt#590]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

-

### Solution Description

In addition to trivy vulnerabilityreports it should be possible to analyze trivy configauditreports.
configauditreports are also CRs like vulnerabilityreports. their fields a a little bit different and the AI prompt for configauditreports must be a little bit different.

kubectl command to get trivy configauditreports:

`kubectl get configauditreports` 

example fields in the .report attribute for the configauditreport:

```
report:
  checks:
  - category: Kubernetes Security Check
    checkID: KSV001
    description: A program inside the container can elevate its own privileges and
      run as root, which might give the program control over the container and node.
    messages:
    - Container 'my-kubernetes-component' of ReplicaSet 'my-kubernetes-component-5bd8595966'
      should set 'securityContext.allowPrivilegeEscalation' to false
    severity: MEDIUM
    success: false
    title: Process can elevate its own privileges
```

### Benefits

users get additional AI explanation for this config reports

### Potential Drawbacks

-

### Additional Information

-
