### ISSUE TITLE
Unable to install K8S GPT as a container

### ISSUE THREAD

**Issue by veniceofcode** [k8sgpt-ai/k8sgpt#755]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [ ] K8sGPT Operator

### Host OS and its Version

Fedora 38

### Steps to reproduce

```
version: '2'
services:
 k8sgpt:
   image: ghcr.io/k8sgpt-ai/k8sgpt:dev-202304011623
   volumes:
     -  /home/$(whoami)/.k8sgpt.yaml:/home/root/.k8sgpt.yaml
```

### Expected behaviour

expected to have k8s gpt up and running

### Actual behaviour

http server error - no such file found
