### ISSUE TITLE
the --language flag does not work with the azureopenai backend

### ISSUE THREAD

**Issue by herveleclerc** [k8sgpt-ai/k8sgpt#907]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

k8sgpt: 0.3.26 (Homebrew), built at: 2024-01-14T20:28:11Z

### Kubernetes Version

v1.27.7

### Host OS and its Version

MacOS

### Steps to reproduce

I have configured 2 backend
```
ai:
    providers:
        - name: azureopenai
          model: gpt-4
          password: xxxxxx
          baseurl: https://xxxxx.openai.azure.com/
          engine: gpt-4
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
        - name: openai
          model: gpt-3.5-turbo
          password: sk-xxxxx
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
    defaultprovider: ""
kubeconfig: ""
kubecontext: ""
```

When i try this : 

```
k8sgpt analyze -b azureopenai --language "French"  --explain --with-doc --no-cache
AI Provider: azureopenai

0 cluster-api-provider-vcluster-system/cluster-api-provider-vcluster-metrics-service(cluster-api-provider-vcluster-metrics-service)
- Error: Service has no endpoints, expected label control-plane=controller-manager
Error: The Service is looking for Pods with the label control-plane=controller-manager but none are found, so it has no endpoints to route traffic to.

Solution:
1. Verify Pod labels with `kubectl get pods --show-labels`.
2. If missing, label Pods using `kubectl label pods <pod-name> control-plane=controller-manager`.
3. Check Service selector matches Pod labels with `kubectl describe service <service-name>`.
```

But i get this with openai :

```
k8sgpt analyze -b openai --language "French"  --explain --with-doc
AI Provider: openai

0 cluster-api-provider-vcluster-system/cluster-api-provider-vcluster-metrics-service(cluster-api-provider-vcluster-metrics-service)
- Error: Service has no endpoints, expected label control-plane=controller-manager
Error: Le service n'a pas de points de terminaison, l'étiquette control-plane=controller-manager est attendue.
Solution:
1. Vérifiez si le label "control-plane=controller-manager" est correctement appliqué au contrôleur de gestion.
2. Assurez-vous que le contrôleur de gestion est en cours d'exécution et accessible.
3. Vérifiez si les points de terminaison du service sont correctement configurés et qu'ils correspondent au label attendu.
4. Redémarrez le service ou le contrôleur de gestion si nécessaire.
```

is it related to the prompt formating ? 

### Expected behaviour

French output when using azureopenai

### Actual behaviour

English output when using azureopenai even i specify --language flag
