### ISSUE TITLE
 failed while calling AI provider openai

### ISSUE THREAD

**Issue by Aman123lug** [k8sgpt-ai/k8sgpt#946]
failed while calling AI provider openai: error, status code: 401, message: Incorrect API key provided: fake. You can find your API key at https://platform.openai.com/account/api-keys.

I changed the Openai API key three to four times again and again it showed the same error that I mentioned.
command of adding API key ``` k8sgpt auth add openai ```

![image](https://github.com/k8sgpt-ai/k8sgpt/assets/94223645/68852c51-db17-46b7-a95e-207931f15fe9)

Why it's happening ? how to fix this

**Comment by VaibhavMalik4187** [comment]
The backend configs are stored in the following fashion:

```yaml
ai:
    providers:
        - name: openai
          password: pass
          model: gpt-3.5-turbo
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
    defaultprovider: ""
```

However, running `k8sgpt auth add` again and again would modify the config file in the following manner:
```yaml
ai:
    providers:
        - name: openai
          password: pass
          model: gpt-3.5-turbo
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
        - name: openai
          password: pass2
          model: gpt-3.5-turbo
          temperature: 0.7
          topp: 0.5
          maxtokens: 2048
    defaultprovider: ""
```

And it'll keep using the old API key as password and this is why you're getting the same error again and again.

I'm working on adding many to one auth: provider mapping to k8sgpt. I've already addressed this issue in https://github.com/k8sgpt-ai/k8sgpt/pull/929
